### PR TITLE
Add trinary exercise

### PR DESCRIPTION
**Pull request by haus**
This adds a trinary exercise to the clojure track. The tests were ported
from [xruby](https://github.com/exercism/xruby/blob/master/trinary/trinary_test.rb).

### CODE REVIEW

**Comment by yurrriq** [comment]
It might be cool to do this in one pass, rather than `re-seq`, `num->digits`, `reverse` `map-indexed` and `apply`. [`.compareTo`][1] can come in handy too.

[1]: http://docs.oracle.com/javase/8/docs/api/java/lang/Character.html#compareTo-java.lang.Character-

**Comment by yurrriq** [comment]
I went ahead and made the changes and merged #90. Thanks!

**Comment by haus** [comment]
Ah nice. compareTo avoids the need turn it into an integer. I like the destructuring too; it didn't occur to me to use it with strings.

**Comment by yurrriq** [comment]
Gotta love the `seq` abstraction.

**Pull request closed without merging**
