### PR TITLE
Add all-your-base exercise

### PR DESCRIPTION
**Pull request by haus**
This commit adds the all-your-base exercise, with the tests ported from
the ruby version of the exercise.

### CODE REVIEW

**Comment by yurrriq** [comment]
Hey, thanks! First, I think you'll need to rename `all_your_base.clj` to `example.clj` to get the tests passing. And then I think it'd be good to keep the function arguments on one line instead of one per argument, e.g.

```clj
[x y z]
;; instead of
[x
 y
 z]
```

**Comment by yurrriq** [comment]
The `(->> ...)` form in the `:else` clause of `convert`'s `cond` looks misaligned, at least on mobile, so maybe double check that too and reindent as necessary.

**Comment by haus** [comment]
Thanks for the quick feedback. I pushed out a commit that should resolve it. Happy to squash that into the previous commit if travis passes.

**Comment by yurrriq** [comment]
LGTM, thanks!

**Pull request merged**
