### PR TITLE
Adds an implementation of POV

### PR DESCRIPTION
**Pull request by alexkalderimis**
This is an implementation of the POV task discussed in exercism/x-common#70

### CODE REVIEW

**Comment by alexkalderimis** [comment]
Do let me know what I need to do to get your Travis build to pass.

**Comment by kytrinyx** [comment]
```
$ bin/configlet .
Evaluating .
-> config.json does not include [pov].
```
The travis build is complaining that the exercise is not in the config, so it wouldn't be added to the track.

This is the config file in question:

https://github.com/exercism/xclojure/blob/master/config.json

Also, you can run `bin/fetch-configlet`, which should give you the validation tool locally. That might not be documented anywhere yet, though.

**Comment by alexkalderimis** [comment]
Fantasti c, thanks.

**Comment by kytrinyx** [comment]
Sorry, I dropped the ball on this. @canweriotnow would you give this a look? If you like it I'll rebase, squash, and merge.

**Comment by canweriotnow** [comment]
:+1:

**Comment by canweriotnow** [comment]
It all looks good to me. I haven't run it, but it's very readable and well-written, so I'll trust the CI.

**Comment by kytrinyx** [comment]
Merged in e1389c0f38f3b2154acd501bdfe23c82783cf748

**Comment by alexkalderimis** [comment]
thanks

**Pull request closed without merging**
