### PR TITLE
WIP: Enable Travis tests

### PR DESCRIPTION
**Pull request by yurrriq**
See #64 for discusson.

**Note**: need to tweak `.travis.yml` so don't merge yet.

### CODE REVIEW

**Comment by yurrriq** [comment]
What does configlet do? Is it necessary?

**Comment by yurrriq** [comment]
^ False positive. scrabble-score-test fails.

**Comment by kytrinyx** [comment]
Yeah, [configlet](https://github.com/exercism/configlet/blob/master/README.md) is necessary. It catches exercism-level problems (as opposed to language-level problems):

* The config.json might be invalid.
* Problems might be missing an example solution.
* Problems might be implemented (test suite + example solution), but not configured.
* Slugs in the configuration might not have a corresponding problem.

**Comment by yurrriq** [comment]
Duly noted. Thanks!

**Comment by yurrriq** [comment]
Merging this. :tada:

**Pull request merged**
