### PR TITLE
Add ABOUT.md and update RESOURCES.md

### PR DESCRIPTION
**Pull request by Teapane**
Updates documentation for `ABOUT.MD` & `RESOURCES.MD`.

[Addresses issue #82](https://github.com/exercism/xclojure/issues/82)

### CODE REVIEW

**Comment by yurrriq** [comment]
Hey, thanks, @Teapane. I've made a few minor suggestions, but other than that this looks great. Thanks for taking the initiative here.

**Comment by Teapane** [comment]
Thanks for the comments @yurrriq; I've `amended` the commit.
 :+1:

**Comment by yurrriq** [comment]
Awesome, thanks again!

**Comment by Teapane** [comment]
No problem! Thanks for merging.

**Pull request merged**
