### PR TITLE
[WIP] Restructure

### PR DESCRIPTION
**Pull request by yurrriq**
See #84.

- [x] Restructure every exercise directory
- [x] Update every project.clj
- [x] Update [_test/check_exercises.clj](https://github.com/exercism/xclojure/blob/master/_test/check_exercises.clj)
- [x] Update `*/test/*_test.clj`
- [x] Update pertinent documentation
- [ ] :shipit:

### CODE REVIEW

**Comment by yurrriq** [comment]
@exercism/track-maintainers, Can someone else look this over?

cc: @kytrinyx

**Comment by yurrriq** [comment]
Should we mention `lein auto test` via [`lein-auto`](https://github.com/weavejester/lein-auto)?

**Comment by yurrriq** [comment]
I mean, this is a big change, but I'm confident it's good to go. :shipit:

**Comment by kytrinyx** [comment]
This looks excellent! :tada:

**Pull request merged**
