### PR TITLE
Create LEARNING.md

### PR DESCRIPTION
**Pull request by degustaf**

### CODE REVIEW

**Comment by degustaf** [comment]
Would Close Issue #82

**Comment by yurrriq** [comment]
Thanks, @degustaf! LGTM at a cursory glance. @kytrinyx, is this the correct general form?

**Comment by kytrinyx** [comment]
Yepp. Usually I try to put stuff that's specific to learning a language in `LEARNING` and stuff that anyone writing clojure might use (docs, linters, tools, etc) under `RESOURCES`, but the line is a bit vague.

**Comment by yurrriq** [comment]
:+1: I've made a few tweaks and added some more links. Thanks again, @degustaf!

**Pull request merged**
