### PR TITLE
use re-seq

### PR DESCRIPTION
**Pull request by achengs**

### CODE REVIEW

**Comment by kytrinyx** [comment]
Thank you!

**Comment by kytrinyx** [comment]
BTW - I've given you commit to the repo. Thanks so much for your contributions lately!

**Comment by achengs** [comment]
I took a quick look at the contributing guide but didn't see anything about peer review before merges. None is required?

**Comment by kytrinyx** [comment]
Peer review is preferred where possible. I've also invited @canweriotnow to this repository, so that you both can review.

**Pull request merged**
