### PR TITLE
[sublist] exercise

### PR DESCRIPTION
**Pull request by leetwinski**

### CODE REVIEW

**Comment by leetwinski** [comment]
Hi @exercism/clojure ! Would you have a chance to check it out?

**Comment by yurrriq** [comment]
This looks a bit off to me for some reason I can't name. Bear in mind I don't write much "real" Clojure anymore. @jjl?

**Comment by yurrriq** [comment]
Are you satisfied with this @leetwinski? If so, I can merge.

**Comment by leetwinski** [comment]
@yurrriq . Oops.. sorry, didn't have any time to fix this. I will update the example, if you (or someone else) give me any clue.

**Comment by leetwinski** [comment]
maybe i should refactor the tuple to be the map for readability?

**Comment by yurrriq** [comment]
Does the `(some #{...} ...)` idiom apply here?

**Comment by yurrriq** [comment]
Bump. This'll need a rebase at least. Have you given any more thought to refactoring? Note the the config.json change will need to be amended per #143.

**Comment by yurrriq** [comment]
ping

**Comment by haus** [comment]
I'm going to close this out as it hasn't had any activity in a few months. If you'd like a hand resolving the conflicts with config.json I'd be happy to help.

**Pull request closed without merging**
